apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: fi97n5rvo-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jsmid/rhtap-qe-java-quarkus:52a0c750707b1400b21b5c20d5b0520798063bed@sha256:ea6e5de1f52985b806b2fb4d3c4f6c4b6b7d971e45219ace896f56eb08649b45
          name: container-image
